apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-service
  labels:
    app: profile-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-service
  template:
    metadata:
      labels:
        app: profile-service
    spec:
      containers:
        - name: profile-service
          image: kweet.azurecr.io/profile:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
          env:
          - name: MONGO_URL
            valueFrom:
              configMapKeyRef:
                name: mongo-config
                key: mongo-url
          - name: MONGO_USER
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongo-user
          - name: MONGO_PASS
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongo-pass
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: profile-service
spec:
  selector:
    app: profile-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
