# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI profileservice

on:
  push:
    branches: [ "main" ]
  pull_request:
      types: [opened, synchronize, reopened]

env:
  MONGO_USER: ${{ secrets.MONGO_DB_USER }}
  MONGO_PASS: ${{ secrets.MONGO_DB_PASSWORD }}
  MONGO_URL: ${{ secrets.MONGO_DB_URL }}

jobs:
  build:
    name: CI and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: './profileservice/package-lock.json'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get master
      run: git fetch origin main
    - name: Install dependencies
      run:  npm install
    - name: Install Jest globally
      run:  sudo npm install -g jest
    - name: Run Tests
      run:  npm run test
      continue-on-error: true
    - name: LS R
      run: ls -R
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
